#!/usr/bin/env node
import {readFileSync,writeFileSync,mkdtempSync,renameSync,rmSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {parseConcepts,normalizeLabel,POLICY_VERSION} from '../lib/concept-policy.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const sourceCommit='04ff0a546d4e55038fa75881ec245662ac5765e9';
const read=path=>readFileSync(join(root,path),'utf8');
const outputs=new Map();
try{
  const domains=read('plugin/references/domains.txt'),concepts=read('plugin/references/concepts.txt');
  const allowed=[['quantum','molecular','human','ecological','geological','cosmic'],['living','mineral','fluid','social','symbolic','mechanical'],['measuring','building','healing','performing','governing','preserving'],['ancient-craft','industrial','contemporary','frontier']];
  const seen=new Set(),specialist=[];
  for(const [offset,line]of domains.split(/\r?\n/u).entries()){
    if(!line.trim()||line.trimStart().startsWith('#'))continue;
    const fields=line.split(' | ').map(x=>x.trim());
    if(fields.length!==5||fields.some(x=>!x)||/[\u0000-\u001f\u007f]/u.test(line))throw new Error(`invalid specialist fields at line ${offset+1}`);
    if(!fields.slice(1).every((value,i)=>allowed[i].includes(value)))throw new Error(`invalid specialist category at line ${offset+1}`);
    const key=normalizeLabel(fields[0]);if(seen.has(key))throw new Error(`normalized duplicate specialist: ${fields[0]}`);seen.add(key);
    specialist.push({id:'specialist-'+sha(key).slice(0,24),value:fields[0],tags:{scale:fields[1],medium:fields[2],activity:fields[3],era:fields[4]},source:{path:'plugin/references/domains.txt',line:offset+1}});
  }
  if(specialist.length!==378)throw new Error('the initial v2 snapshot must retain all 378 legacy specialist entries');
  const concept=parseConcepts(concepts).map(({value,tier,facet,sourceLine})=>({id:'concept-'+sha(normalizeLabel(value)).slice(0,24),value,tags:{tier,facet},source:{path:'plugin/references/concepts.txt',line:sourceLine}}));
  if(concept.length!==461)throw new Error('the initial v2 snapshot must retain all 461 legacy concepts');
  const lenses=read('plugin/scripts/draw-legacy.sh').match(/^LENSES="([^"]+)"$/m)?.[1].split(' ');
  if(!lenses||lenses.length!==8||new Set(lenses).size!==8)throw new Error('expected the eight historical lenses');
  const corpus={schemaVersion:2,corpusVersion:'corpus-v2-2026-09-20',sourceCommit,policyVersion:POLICY_VERSION,
    provenance:{specialistSourceSha256:sha(domains),conceptSourceSha256:sha(concepts),conceptAcquisition:'Committed 2026-06-12 title snapshot and editorial curation; individual Wikipedia revisions were not recorded.'},
    lensVersion:'lenses-v1',lenses,pools:{specialist,concept}};
  const json=JSON.stringify(corpus,null,2)+'\n',digest=sha(json);
  const module=`// GENERATED by plugin/scripts/build-corpus.mjs; do not edit.\nexport const CORPUS_SHA256 = ${JSON.stringify(digest)};\nexport const CORPUS = ${JSON.stringify(corpus)};\n`;
  outputs.set('plugin/references/corpus-v2.json',json);outputs.set('plugin/lib/corpus-v2.mjs',module);outputs.set('site/js/corpus-v2.js',module);
  outputs.set('site/js/sampler-v2.js','// GENERATED from plugin/lib/sampler-v2.mjs; do not edit.\n'+read('plugin/lib/sampler-v2.mjs').replace("from './corpus-v2.mjs'","from './corpus-v2.js'"));
  if(process.argv.includes('--legacy-site')){
    const sum=spawnSync('cksum',[],{input:domains+concepts,encoding:'utf8'});if(sum.status!==0)throw new Error('cksum failed while building legacy provenance');
    const stamp=sum.stdout.trim().split(/\s+/)[0];
    const legacy='// GENERATED by scripts/gen_site_data.sh - do not edit by hand.\n'+
      `export const PROVENANCE = { source: "references/domains.txt", count: ${specialist.length}, concepts: ${concept.length}, stamp: "${stamp}" };\n`+
      `export const LENSES = [${lenses.map(JSON.stringify).join(', ')}];\n`+
      `export const DOMAINS = [\n  ${specialist.map(x=>JSON.stringify(x.value)).join(',\n  ')}\n];\n`+
      `export const CONCEPTS = [\n  ${concept.map(x=>JSON.stringify(x.value)).join(',\n  ')}\n];\n`;
    outputs.set('site/js/domains.js',legacy);
  }
  if(process.argv.includes('--check')){
    for(const [path,value]of outputs)if(read(path)!==value)throw new Error(`generated file is stale: ${path}`);
    console.log('corpus and browser sampler artifacts are current');
  }else{
    // Validate and serialize all outputs before touching any destination; replace each atomically.
    for(const [path,value]of outputs){const target=join(root,path),tmp=mkdtempSync(join(dirname(target),'.wildcard-build-'));try{const stage=join(tmp,'data');writeFileSync(stage,value);renameSync(stage,target);}finally{rmSync(tmp,{recursive:true,force:true});}}
    console.log(`generated v2 snapshot: ${specialist.length} specialists, ${concept.length} concepts; sha256 ${digest}`);
  }
}catch(e){console.error(`build-corpus: ${e.message}`);process.exitCode=1;}
