#!/usr/bin/env bash
# Generate site/js/domains.js from references/domains.txt (tag-stripped, order-preserved)
# and the LENSES set from scripts/draw.sh. Never hand-edit the output.
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/references/domains.txt"
DRAW="$ROOT/scripts/draw.sh"
OUT="$ROOT/site/js/domains.js"
COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"

# Tag-strip with the same awk logic draw.sh uses (field 1 of " | "-separated lines),
# preserving line order so browser indices match shell indices.
domains_json="$(grep -vE '^[[:space:]]*($|#)' "$SRC" \
  | awk 'BEGIN{ORS=""} { sub(/[[:space:]]*\|.*/,""); sub(/[[:space:]]+$/,"");
      gsub(/\\/,"\\\\"); gsub(/"/,"\\\"");
      printf "%s\"%s\"", (NR>1?",\n  ":""), $0 }')"
count="$(grep -vcE '^[[:space:]]*($|#)' "$SRC")"
lenses="$(sed -n 's/^LENSES="\(.*\)"$/\1/p' "$DRAW")"
lenses_json="$(printf '%s' "$lenses" | awk '{for(i=1;i<=NF;i++) printf "%s\"%s\"", (i>1?", ":""), $i}')"

{
  echo "// GENERATED by scripts/gen_site_data.sh — do not edit by hand."
  echo "export const PROVENANCE = { source: \"references/domains.txt\", count: $count, commit: \"$COMMIT\" };"
  echo "export const LENSES = [$lenses_json];"
  echo "export const DOMAINS = ["
  echo "  $domains_json"
  echo "];"
} > "$OUT"
echo "wrote $OUT ($count domains)"
