#!/usr/bin/env bash
# Generate site/js/domains.js from references/domains.txt (tag-stripped, order-preserved)
# and the LENSES set from scripts/draw.sh. Never hand-edit the output.
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/plugin/references/domains.txt"
CONCEPTS_SRC="$ROOT/plugin/references/concepts.txt"
DRAW="$ROOT/plugin/scripts/draw.sh"
OUT="$ROOT/site/js/domains.js"
# Stamp the POOLS, not the commit. A commit hash written here is stale the moment it is
# committed (the stamp names the parent of the commit that carries it), and the page was
# shipping "@ 2f5e700" for an object that never existed in the repo - a dangling citation
# on the one page whose whole argument is that its claims check out. A cksum over the two
# pool files names exactly what the page draws from, and anyone can reproduce it:
#   cat plugin/references/domains.txt plugin/references/concepts.txt | cksum
STAMP="$(cat "$SRC" "$CONCEPTS_SRC" | cksum | awk '{print $1}')"

# Tag-strip with the same awk logic draw.sh uses (field 1 of " | "-separated lines),
# preserving line order so browser indices match shell indices.
domains_json="$(grep -vE '^[[:space:]]*($|#)' "$SRC" \
  | awk 'BEGIN{ORS=""} { sub(/[[:space:]]*\|.*/,""); sub(/[[:space:]]+$/,"");
      gsub(/\\/,"\\\\"); gsub(/"/,"\\\"");
      printf "%s\"%s\"", (NR>1?",\n  ":""), $0 }')"
count="$(grep -vcE '^[[:space:]]*($|#)' "$SRC")"
# Same tag-strip for the concept pool, so CONCEPTS indices match shell concept-mode picks.
concepts_json="$(grep -vE '^[[:space:]]*($|#)' "$CONCEPTS_SRC" \
  | awk 'BEGIN{ORS=""} { sub(/[[:space:]]*\|.*/,""); sub(/[[:space:]]+$/,"");
      gsub(/\\/,"\\\\"); gsub(/"/,"\\\"");
      printf "%s\"%s\"", (NR>1?",\n  ":""), $0 }')"
concepts_count="$(grep -vcE '^[[:space:]]*($|#)' "$CONCEPTS_SRC")"
lenses="$(sed -n 's/^LENSES="\(.*\)"$/\1/p' "$DRAW")"
lenses_json="$(printf '%s' "$lenses" | awk '{for(i=1;i<=NF;i++) printf "%s\"%s\"", (i>1?", ":""), $i}')"

{
  echo "// GENERATED by scripts/gen_site_data.sh - do not edit by hand."
  echo "export const PROVENANCE = { source: \"references/domains.txt\", count: $count, concepts: $concepts_count, stamp: \"$STAMP\" };"
  echo "export const LENSES = [$lenses_json];"
  echo "export const DOMAINS = ["
  echo "  $domains_json"
  echo "];"
  echo "export const CONCEPTS = ["
  echo "  $concepts_json"
  echo "];"
} > "$OUT"
echo "wrote $OUT ($count domains, $concepts_count concepts)"
